### PR TITLE
Add Mqtt functionalities

### PR DESCRIPTION
**Pull request by nagydavid**
@solmoller 
Hejsa,

I added an Mqtt functionalities with home assistant auto discovery config. Therefor it became more smart home software agnostic.

I wrote in PERL the first time in my life, so there could be a way to write it more elegantly. I tried to implement without shell scripts but all PERL-MQTT libraries were a little bit confusing, and it just added extra complexity.

I hope it helps some people.

Output in Home Assistant as a device and its entities
image

### CODE REVIEW

**Comment by nagydavid** [comment]
Apart from this I have an issue.: 

- after night when the solar inverter turns on again (during the night it is turning completely off, so assuming this is how it should work) the scripts does not update anymore, so I am interested did @solmoller it is a bug, or my settings are wrong.

**Comment by solmoller** [comment]
That is very interesting. I went via Pvoutput:
 - platform: pvoutput
    system_id: xxx
    api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - platform: template
    sensors:
      power_consumption:
        value_template: >
          {% set pc = state_attr('sensor.pvoutput', 'power_consumption') %}
          {{ '0' if pc == 'NaN' else pc }}
        friendly_name: 'Using'
        unit_of_measurement: 'Watt'
      energy_consumption:
        value_template: "{{ '{:.1f}'.format(state_attr('sensor.pvoutput', 'ene$
        friendly_name: 'Used'
        unit_of_measurement: 'kWh'
      power_generation:
        value_template: >
          {% set pg = state_attr('sensor.pvoutput', 'power_generation') %}
          {{ '0' if pg == 'NaN' else pg }}

But you get more data out, and I already use MQTT intensely. 

As for the potential bug, I don't have that problem, so it's probably your code. I'll try to find time to debug

BR

Henrik

**Comment by nagydavid** [comment]
Thanks for looking at it. 
I did it because I want to have as less cloud polling as possible  :)

**Comment by sorentorp** [comment]
Great work! Lets get it merged :-)

**Comment by solmoller** [comment]
> Great work! Lets get it merged :-)

Jeg har ikke haft tid til at teste, hvis I siger det virker skal jeg nok merge...

**Comment by solmoller** [comment]
Whoops, in english: I haven't had the time to test, and David has implied issues with the code - if all is well I'll gladly merge

**Comment by sorentorp** [comment]
@nagydavid and @solmoller I did some testing.

I dont use u/pw for my mqtt - and that seems to be mandatory with this implementation. And so does the model name.

> pi@raspberrypi:~/eversolar-monitor $ perl eversolar.pl
> mqtt_inverter_model expects an argument at eversolar.ini line 51
> mqtt_user expects an argument at eversolar.ini line 54
> mqtt_password expects an argument at eversolar.ini line 55
> 2022-01-03 00:49:12: Severity 1, Configfile is: eversolar.ini

**Comment by sorentorp** [comment]
I just used default username + password and my modelnumber "TL3000". 

I also had to run "sudo apt-get install mosquitto-clients"

**Comment by sorentorp** [comment]
Screenshot 2022-01-03 09 53 08

**Comment by sorentorp** [comment]
also the loglevel should be adjusted.

> 2022-01-03 09:58:15: Severity 1: Mqtt messages published
> 2022-01-03 09:58:30: Severity 1: Mqtt messages published
> 2022-01-03 09:58:45: Severity 1: Mqtt messages published
> 2022-01-03 09:59:00: Severity 1: Mqtt messages published
> 2022-01-03 09:59:17: Severity 1: Mqtt messages published
> 2022-01-03 09:59:32: Severity 1: Mqtt messages published
> 2022-01-03 09:59:48: Severity 1: Mqtt messages published
> 2022-01-03 10:00:03: Severity 1: Mqtt messages published

My settings are
> debug = 1       # Debug level , 0 = none, 1 is high priority, 3 is everything, 4 also output

**Comment by sorentorp** [comment]
And AC Current should be "A" - not "V"

>  elsif ( $_[0] eq "iac" ){
>                             $config_data{'icon'} = "mdi:current-ac";
>                             $config_data{'name'} = "AC Current";
>                             $config_data{'unit_of_measurement'} = "V";    <-------
>                             $config_data{'device_class'} = "current";

**Comment by nagydavid** [comment]
@solmoller @sorentorp 
tak for din anmeldelse af PR. Jeg bor i Danmark, så jeg kan forstå lidt dansk :P.
About the PR, I will update the spelling errors, and make sure that u/p will be requested if it has any value.

**Comment by solmoller** [comment]
Thanks, I'll test shortly. Maybe we should add instructions on how to setup HASS?

**Comment by sorentorp** [comment]
A MQTT Broker and Hass - https://www.home-assistant.io/docs/mqtt/broker/

**Comment by nagydavid** [comment]
If the Mosquito broker is set up, then the eversolar.pl will send discovery messages so there will be no need for additional templates sensors in hass. Only the mqtt discovery needs to be enabled in the eversolar.ini .

**Comment by solmoller** [comment]
Thanks, I figured it out


Brilliant!

BR Henrik

lør. d. 8. jan. 2022 22.59 skrev sorentorp ***@***.***>:

**Pull request merged**
